#include<mp/user.action>

var activityId = context.parameters.get("activity");
if(null == activityId) {
    return "error.json";
}
activityId = parseInt(activityId);
var chartId = context.parameters.get("id");
if(null == chartId || "" == chartId) {
    chartId = 0;
}
else {
    chartId = parseInt(chartId);
}
var activity = $("ActivityDetail", "id = " + activityId);
if(null == activity) {
    return "error.json";
}
var charts = activity.c("listen", chartId, context.get("userId"));
for(var i = 0; i < charts.length; i++) {
    var chart = charts[i];
    chart.setContent(chart.content().replace("\"", "\\\"").replace("#", "\\#").replace("$", "\\$"));
}
context.set("charts", charts);
//
var user = context.get("User");
context.set("userId", context.get("userId"));
var angel = null;
var winner = null;
if(user.p("id") == activity.p("angelId")) {
    angel = user;
    var deal = activity.r("deal");
    if(null != deal) {
        winner = deal.r("user");
    }
}
else {
    angel = activity.r("angel");
    winner = user;
}
context.set("angelId", angel.p("id"));
context.set("mockName", activity.p("mockName"));
context.set("angelPhoto", activity.c("primaryPhoto"));
if(null == winner) {
    context.set("bidderId", 0);
    context.set("bidderNickName", "竞拍人");
    context.set("bidderPhoto", "/image/photo.png");
}
else {
    context.set("bidderId", winner.p("id"));
    context.set("bidderNickName", winner.p("nickName"));
    context.set("bidderPhoto", winner.c("primaryPhoto"));
}
return "chart.json";
