#include<mp/user.action>
var activityId = context.parameters.get("activity");
if(null == activityId || "" == activityId) {
    return "error.html";
}
activityId = parseInt(activityId);
context.set("activityId", activityId);
return "chart.html";
