#include<mp/user.action>

var city = context.cookie.get("city");
if(null == city || "" == city) {
    return "activities.html";
}
var cityId = eval("(" + city.trim() + ")").id;
var cityName = eval("(" + city.trim() + ")").name;
context.set("cityName", cityName);
var type = context.parameters.get("type");
if(null == type || "" == type) {
    var user = context.get("User");
    var gender = user.p("gender");
    if(1 == gender) {
        type = 1;
    }
    else if(2 == gender) {
        type = 2;
    }
    else {
        type = 1;
    }
}
else {
    type = parseInt(type);
}
context.set("type", type);
var page = context.parameters.get("page");
if(null == page || "" == page) {
    page = 0;
}
else {
    page = parseInt(page) - 1;
    if(page < 0) {
        page = 0;
    }
}
var size = 10;
var stage = $("Stage", "");
context.set("activities", stage.c("search", cityId, type, page * size, size));
return "activities.html";
