#include<mp/fans.action>

var city = context.cookie.get("city");
if(null == city || "" == city) {
    return "city.url";
}
var cityId = eval("(" + city.trim() + ")").id;
context.set("cityId", cityId);
var cityName = eval("(" + city.trim() + ")").name;
context.set("cityName", cityName);
//
var user = context.get("User");
context.set("user", user);
return "organize.html";
