#include<mp/user.action>

var activityId = context.parameters.get("activity");
if(null == activityId || "" == activityId) {
    context.set("msg", "未选择活动");
    return "error.json";
}
activityId = parseInt(activityId);
var content = context.parameters.get("content");
if(null == content || "" == content) {
    context.set("msg", "请输入评论内容");
    return "error.json";
}
var anonymous = context.parameters.get("anonymous");
if("true" == anonymous) {
    anonymous = true;
}
else {
    anonymous = false;
}
var comment = $("Comment", "activityId = " +　activityId);
if(true == comment.c("submit", context.get("userId"), content, anonymous)) {
    context.set("code", 0);
    return "success.json";
}
else {
    context.set("code", -1);
    context.set("msg", "提交失败，请控制频次");
    return "error.json";
}
