#include<manage/authority.action>

var activityApproval = $("ActivityApproval", null);
if(null == activityApproval) {

}
else {
    context.set("activity", activityApproval);
}
return "approval.html";
